import {input,modal,closeOnCancel,num,clamp,esc,toast} from './editor-helpers.js';
import {uid} from './utils.js';

export function renderGraduatePanel(p,ctx){renderRecords(p,ctx,{title:'Graduates',items:ctx.state.graduates,collection:'graduates',label:x=>x.name,fields:[['Name','name',160],['Program / credential','program',300],['K9 / team','k9',200],['Recognition statement','statement',1000],['Photo URL','photoUrl',2048]]})}
export function renderAwardPanel(p,ctx){renderRecords(p,ctx,{title:'Awards',items:ctx.state.awards,collection:'awards',label:x=>x.name,fields:[['Award name','name',200],['Recipient','recipient',200],['Citation','citation',1000],['Background image URL','imageUrl',2048]]})}
export function renderMusicPanel(p,ctx){renderRecords(p,ctx,{title:'Music tracks',items:ctx.state.tracks,collection:'tracks',label:x=>x.title,fields:[['Track title','title',200],['Audio URL','url',2048]],after:'<div class="notice">For browser autoplay compliance, press <b>Arm event audio</b> once on the Audience Display before scheduled music is expected to start. Mode-specific cues are assigned in the Event panel.</div>'})}
function renderRecords(p,ctx,{title,items,collection,label,fields,after=''}){
 p.innerHTML=`<div class="panel-head"><h2 class="section-title">${esc(title)} · ${items.length}</h2><button class="btn primary" id="addRecord">Add</button></div><div class="item-list">${items.map(x=>`<article class="item-card" data-id="${esc(x.id)}"><div class="item-card-head"><b>${esc(label(x)||x.id)}</b><div class="toolbar"><button class="btn edit">Edit</button><button class="btn danger remove">Remove</button></div></div></article>`).join('')}</div>${after}`;
 p.querySelector('#addRecord').onclick=()=>open({id:uid(collection.slice(0,-1)),order:(items.at(-1)?.order||0)+1,enabled:true});
 p.querySelectorAll('[data-id]').forEach(row=>{const x=items.find(i=>i.id===row.dataset.id);row.querySelector('.edit').onclick=()=>open(x);row.querySelector('.remove').onclick=async()=>{if(confirm('Remove this item?'))await ctx.backend.deleteDoc(ctx.eventId,collection,x.id)}});
 function open(x){const m=modal(title,`<div class="stack">${fields.map(([l,k])=>input(l,x[k]||'',k.toLowerCase().includes('url')?'url':'text',`data-field="${k}"`)).join('')}${input('Order',x.order||items.length+1,'number','id="recordOrder" min="1" max="999"')}<div class="field check"><label><input id="recordEnabled" type="checkbox" ${x.enabled!==false?'checked':''}> Enabled</label></div></div><div class="toolbar" style="margin-top:16px"><button class="btn primary" data-save>Save</button><button class="btn" data-cancel>Cancel</button></div>`);closeOnCancel(m);m.querySelector('[data-save]').onclick=async()=>{const data={};for(const [,key,max] of fields)data[key]=m.querySelector(`[data-field="${key}"]`).value.trim().slice(0,max);data.order=clamp(num(m.querySelector('#recordOrder').value,items.length+1),1,999);data.enabled=m.querySelector('#recordEnabled').checked;await ctx.backend.putDoc(ctx.eventId,collection,x.id,data);m.remove();toast(`${title.slice(0,-1)} saved`)}}
}
